version: '3.9'
services:
  php:
    build: .
    ports:
      - 4000:80
    volumes:
      - ./Source/:/var/www/html
    network_mode: bridge
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3010:3010
    volumes:
      - slotMachineData:/var/lib/mysql
    network_mode: bridge
    environment:
      - MARIADB_ROOT_PASSWORD=value
volumes:
  slotMachineData:
    name: db-data-slot-machine